Add missing backslash to helm upgrade command
Or else the helm command will fail with:

```txt
Error: "helm upgrade" requires 2 arguments

Usage:  helm upgrade [RELEASE] [CHART] [flags]
no such file or directory: prometheus-msteams/prometheus-msteams
```